# All env variables that are used in one place
# This is for deployment-specific values, which may be managed by other teams
env:
  db:
    host: jdbc:postgresql://${DATABASE_HOSTNAME:127.0.0.1}:5432
    init: ${INIT_DB:false}
    upgrade: ${UPGRADE_DB:false}
    catalog:
      name: ${DATABASE_NAME:catalog_db}
      pass: ${DATABASE_USER_PASSWORD:dbpwd}
      user: ${DATABASE_USER:dbuser}
  tracing:
    exportEnabled: ${CLOUD_TRACE_ENABLED:false}
    samplingRate: ${SAMPLING_PROBABILITY:0}
  sam:
    basePath: ${SAM_ADDRESS:https://sam.dsde-dev.broadinstitute.org}
    resourceId: ${SAM_RESOURCE_ID:catalog-dev}
  datarepo:
    basePath: ${DATAREPO_ADDRESS:https://jade.datarepo-dev.broadinstitute.org}
  rawls:
    basePath: ${RAWLS_ADDRESS:https://rawls.dsde-dev.broadinstitute.org}

# Below here is non-deployment-specific

logging.pattern.level: '%X{requestId} %5p'
logging.level.root: 'WARN'

spring:
  application.name: catalog

catalog:

  status-check:
    enabled: true
    pollingIntervalSeconds: 60
    startupWaitSeconds: 5
    stalenessThresholdSeconds: 125

  catalog-database:
    initializeOnStart: ${env.db.init}
    password: ${env.db.catalog.pass}
    upgradeOnStart: ${env.db.upgrade}
    uri: ${env.db.host}/${env.db.catalog.name}
    username: ${env.db.catalog.user}

  sam:
    basePath: ${env.sam.basePath}
    resourceId: ${env.sam.resourceId}

  datarepo:
    basePath: ${env.datarepo.basePath}

  rawls:
    basePath: ${env.rawls.basePath}

  schema:
    basePath: schema/development/schema.json
