openapi: 3.0.3
info:
  title: Terra Data Catalog
  description: |
    An indexed catalog of data for use in Terra.

    ⚠️ Do not add sensitive data. All catalog entries are publicly accessible to all Terra users. ⚠️
  version: 0.0.1
paths:
  /status:
    get:
      summary: Check status of the service
      tags: [ public ]
      operationId: getStatus
      security: [ ]
      responses:
        '200':
          $ref: '#/components/responses/SystemStatusResponse'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/SystemStatusResponse'

  /version:
    get:
      summary: Get version info of the deployed service
      tags: [ public ]
      operationId: getVersion
      security: [ ]
      responses:
        '200':
          description: Version information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionProperties'
        '404':
          description: "Version not configured"
        '500':
          $ref: '#/components/responses/ServerError'

  /api/v1/datasets:
    get:
      summary: Lists the available catalog datasets
      tags: [ datasets ]
      operationId: listDatasets
      responses:
        '200':
          description: A JSON array of catalog datasets
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetsListResponse'
        '500':
          $ref: '#/components/responses/ServerError'
    post:
      summary: Create a new dataset
      tags: [ datasets ]
      description: |
        ⚠️ Do not add sensitive data. All catalog entries are publicly accessible to all Terra users. ⚠️
      operationId: createDataset
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDatasetRequest'
        required: true
      responses:
        200:
          $ref: '#/components/responses/DatasetResponse'
        403:
          description: No permission to modify metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReport'
  /api/v1/datasets/{id}:
    get:
      summary: Given a dataset ID, return its catalog entry
      tags: [ datasets ]
      operationId: getDataset
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          description: A JSON object of the dataset
          content:
            application/json:
              schema:
                type: string
        '404':
          description: "Dataset not found"
        '500':
          $ref: '#/components/responses/ServerError'
    put:
      summary: Update the catalog entry for a dataset
      tags: [ datasets ]
      description: |
        ⚠️ Do not add sensitive data. All catalog entries are publicly accessible to all Terra users. ⚠️
      operationId: updateDataset
      parameters:
        - $ref: '#/components/parameters/Id'
      requestBody:
        description: The catalog entry to replace existing entry for this dataset
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        204:
          description: The catalog entry was updated successfully
          content: { }
        403:
          description: No permission to modify metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReport'
        404:
          description: Not found - dataset id does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReport'
    delete:
      summary: Delete the catalog entry for a dataset
      tags: [ datasets ]
      operationId: deleteDataset
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        204:
          description: The catalog entry was deleted successfully
          content: { }
        403:
          description: No permission to modify metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReport'
        404:
          description: Not found - dataset id does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReport'
  /api/v1/datasets/{id}/tables:
    get:
      summary: Given a dataset ID, return its preview metadata
      tags: [ datasets ]
      operationId: listDatasetPreviewTables
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          description: A JSON object of the preview metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetPreviewTablesResponse'
        '404':
          description: "Dataset not found"
        '500':
          $ref: '#/components/responses/ServerError'

  /api/v1/datasets/{id}/tables/{tableName}:
    get:
      summary: Given a dataset ID and a table name, return a table preview
      tags: [ datasets ]
      operationId: getDatasetPreviewTable
      parameters:
        - $ref: '#/components/parameters/Id'
        - in: path
          name: tableName
          schema:
            type: string
          required: true
      responses:
        '200':
          description: A JSON object of the table preview
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetPreviewTable'
        '404':
          description: "Dataset not found"
        '500':
          $ref: '#/components/responses/ServerError'

components:
  parameters:
    Id:
      name: id
      in: path
      description: A UUID to used to identify an object in the catalog
      required: true
      schema:
        type: string
        format: uuid

  responses:
    SystemStatusResponse:
      description: A JSON description of the subsystems and their statuses.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SystemStatus'
    DatasetResponse:
      description: The created dataset's ID
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreatedDatasetId'


    # Error Responses
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'
    PermissionDenied:
      description: Permission denied
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'
    NotFound:
      description: Not found (or unauthorized)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'
    ServerError:
      description: Server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'

  schemas:
    ErrorReport:
      type: object
      required: [ message, statusCode ]
      properties:
        message:
          type: string
        statusCode:
          type: integer

    SystemStatus:
      required: [ ok, systems ]
      type: object
      properties:
        ok:
          type: boolean
          description: whether any system(s) need attention
        systems:
          type: object
          additionalProperties:
            type: object
            properties:
              ok:
                type: boolean
              messages:
                type: array
                items:
                  type: string

    CreatedDatasetId:
      type: object
      required: [ id ]
      properties:
        id:
          type: string
          format: uuid

    DatasetsListResponse:
      type: object
      required: [ result ]
      properties:
        result:
          type: array
          items:
            type: object
      description: List of catalog datasets

    DatasetAccessLevel:
      type: string
      description: The level of access a user or group has on a Dataset. Owners can create and delete
        dataset entries, writers can modify only, readers can read the data, and discoverers can see
        that the data exists but not read it.
      enum:
        - OWNER
        - READER
        - DISCOVERER

    VersionProperties:
      type: object
      properties:
        gitTag:
          type: string
        gitHash:
          type: string
        github:
          type: string
        build:
          type: string

    CreateDatasetRequest:
      description: |
        ⚠️ Do not add sensitive data. All catalog entries are publicly accessible to all Terra users. ⚠️
      type: object
      properties:
        storageSystem:
          $ref: '#/components/schemas/StorageSystem'
        storageSourceId:
          type: string
        catalogEntry:
          type: string

    DatasetPreviewTablesResponse:
      type: object
      properties:
        tables:
          type: array
          items:
            $ref: '#/components/schemas/TableMetadata'
      description: >
        DatasetPreviewTablesResponse returns information about the table structure of a dataset.

    DatasetPreviewTable:
      type: object
      properties:
        columns:
          type: array
          items:
            $ref: '#/components/schemas/ColumnModel'
        rows:
          type: array
          items:
            type: object

    ColumnModel:
      type: object
      properties:
        name:
          type: string
        array_of:
          type: boolean
          description: if true, this column is an array of data.

    TableMetadata:
      required:
        - name
      type: object
      properties:
        name:
          type: string
        hasData:
          type: boolean

    StorageSystem:
      type: string
      description: The storage system for this dataset
      enum: ['tdr', 'wks', 'ext']

  securitySchemes:
    authorization:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            openid: open id authorization
            email: email authorization
            profile: profile authorization
    bearerAuth:
      type: http
      scheme: bearer

security:
  - authorization: [ openid, email, profile ]
  - bearerAuth: [ ]
