openapi: 3.0.3
info:
  title: Terra Data Catalog
  description: |
    An indexed catalog of data for use in Terra.

    ⚠️ Do not add sensitive data. All catalog entries are publicly accessible to all Terra users. ⚠️
  version: 0.0.1
paths:
  /status:
    get:
      summary: Check status of the service
      tags: [ public ]
      operationId: getStatus
      security: [ ]
      responses:
        '200':
          $ref: '#/components/responses/SystemStatusResponse'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/SystemStatusResponse'

  /version:
    get:
      summary: Get version info of the deployed service
      tags: [ public ]
      operationId: getVersion
      security: [ ]
      responses:
        '200':
          description: Version information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionProperties'
        '404':
          description: "Version not configured"
        '500':
          $ref: '#/components/responses/ServerError'

  /api/v1/datasets:
    get:
      summary: Lists the available catalog datasets
      tags: [ datasets ]
      operationId: listDatasets
      responses:
        '200':
          description: A JSON array of catalog datasets
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetsListResponse'
        '500':
          $ref: '#/components/responses/ServerError'
    post:
      summary: Create a new dataset
      tags: [ datasets ]
      description: |
        ⚠️ Do not add sensitive data. All catalog entries are publicly accessible to all Terra users. ⚠️
      operationId: createDataset
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDatasetRequest'
        required: true
      responses:
        200:
          $ref: '#/components/responses/DatasetResponse'
        403:
          description: No permission to modify metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReport'
  /api/v1/datasets/{id}:
    get:
      summary: Given a dataset ID, return its catalog entry
      tags: [ datasets ]
      operationId: getDataset
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          description: A JSON object of the dataset
          content:
            application/json:
              schema:
                type: string
        '404':
          description: "Dataset not found"
        '500':
          $ref: '#/components/responses/ServerError'
    put:
      summary: Update the catalog entry for a dataset
      tags: [ datasets ]
      description: |
        ⚠️ Do not add sensitive data. All catalog entries are publicly accessible to all Terra users. ⚠️
      operationId: updateDataset
      parameters:
        - $ref: '#/components/parameters/Id'
      requestBody:
        description: The catalog entry to replace existing entry for this dataset
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        204:
          description: The catalog entry was updated successfully
          content: { }
        403:
          description: No permission to modify metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReport'
        404:
          description: Not found - dataset id does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReport'
    delete:
      summary: Delete the catalog entry for a dataset
      tags: [ datasets ]
      operationId: deleteDataset
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        204:
          description: The catalog entry was deleted successfully
          content: { }
        403:
          description: No permission to modify metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReport'
        404:
          description: Not found - dataset id does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReport'
  /api/v1/datasets/{id}/preview-metadata:
    get:
      summary: Given a dataset ID, return its preview metadata
      tags: [ datasets ]
      operationId: getDatasetPreviewMetadata
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          description: A JSON object of the preview metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetPreviewMetadataResponse'
        '404':
          description: "Dataset not found"
        '500':
          $ref: '#/components/responses/ServerError'

components:
  parameters:
    Id:
      name: id
      in: path
      description: A UUID to used to identify an object in the catalog
      required: true
      schema:
        type: string
        format: uuid

  responses:
    SystemStatusResponse:
      description: A JSON description of the subsystems and their statuses.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SystemStatus'
    DatasetResponse:
      description: The created dataset's ID
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreatedDatasetId'


    # Error Responses
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'
    PermissionDenied:
      description: Permission denied
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'
    NotFound:
      description: Not found (or unauthorized)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'
    ServerError:
      description: Server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'

  schemas:
    ErrorReport:
      type: object
      required: [ message, statusCode ]
      properties:
        message:
          type: string
        statusCode:
          type: integer

    SystemStatus:
      required: [ ok, systems ]
      type: object
      properties:
        ok:
          type: boolean
          description: whether any system(s) need attention
        systems:
          type: object
          additionalProperties:
            type: object
            properties:
              ok:
                type: boolean
              messages:
                type: array
                items:
                  type: string

    CreatedDatasetId:
      type: object
      required: [ id ]
      properties:
        id:
          type: string
          format: uuid

    DatasetsListResponse:
      type: object
      properties:
        result:
          type: array
          items:
            type: object
      description: List of catalog datasets

    VersionProperties:
      type: object
      properties:
        gitTag:
          type: string
        gitHash:
          type: string
        github:
          type: string
        build:
          type: string

    CreateDatasetRequest:
      description: |
        ⚠️ Do not add sensitive data. All catalog entries are publicly accessible to all Terra users. ⚠️
      type: object
      properties:
        storageSystem:
          $ref: '#/components/schemas/StorageSystem'
        storageSourceId:
          type: string
        catalogEntry:
          type: string

    DatasetPreviewMetadataResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        tables:
          type: array
          items:
            $ref: '#/components/schemas/TableModel'
        dataProject:
          type: string
          description: Project id of the snapshot data project
      description: >
        DatasetPreviewMetadataResponse returns information about the table structure of a dataset.

    TableModel:
      required:
        - columns
        - name
      type: object
      properties:
        name:
          $ref: '#/components/schemas/ObjectNameProperty'
        columns:
          type: array
          items:
            $ref: '#/components/schemas/ColumnModel'
        primaryKey:
          type: array
          items:
            $ref: '#/components/schemas/ObjectNameProperty'
        partitionMode:
          type: string
          default: none
          enum:
            - none
            - date
            - int
        datePartitionOptions:
          $ref: '#/components/schemas/DatePartitionOptionsModel'
        intPartitionOptions:
          $ref: '#/components/schemas/IntPartitionOptionsModel'
        rowCount:
          type: integer
      description: one table in a schema

    ObjectNameProperty:
      maxLength: 63
      minLength: 1
      pattern: ^[_a-zA-Z0-9][_a-zA-Z0-9]*$
      type: string
      description: >
        Table and column names follow this pattern. It follows BigQuery naming rules. For table and column names, this is shorter than what BigQuery allows.
    TableDataType:
      type: string
      enum: [ string, boolean, bytes, date, datetime, dirref, fileref, float, float64, integer, int64, numeric, record, text, time, timestamp ]
      description: >
        The type of a column in a table.
    ColumnModel:
      required:
        - datatype
        - name
      type: object
      properties:
        name:
          $ref: '#/components/schemas/ObjectNameProperty'
        datatype:
          $ref: '#/components/schemas/TableDataType'
        array_of:
          type: boolean
          description: if true, make this column an array of type datatype.
          default: false
      description: one column of a table
    DatePartitionOptionsModel:
      required:
        - column
      type: object
      properties:
        column:
          $ref: '#/components/schemas/ObjectNameProperty'
      description: Describes how a date partition should be configured.
    IntPartitionOptionsModel:
      required:
        - column
        - interval
        - max
        - min
      type: object
      properties:
        column:
          $ref: '#/components/schemas/ObjectNameProperty'
        min:
          type: integer
          description: >
            The smallest value to partition within the target column. Any rows with a value smaller than this will be unpartitioned.
          format: int64
        max:
          type: integer
          description: >
            The largest value to partition within the target column. Any rows with a value larger than this will be unpartitioned.
          format: int64
        interval:
          type: integer
          description: >
            The size to use when dividing the partitioning range into "buckets". (max - min) / (this value) cannot be larger than 4,000.
          format: int64
      description: Describes how an int partition should be configured.

    StorageSystem:
      type: string
      description: The storage system for this dataset
      enum: ['tdr', 'wks', 'ext']

  securitySchemes:
    authorization:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            openid: open id authorization
            email: email authorization
            profile: profile authorization
    bearerAuth:
      type: http
      scheme: bearer

security:
  - authorization: [ openid, email, profile ]
  - bearerAuth: [ ]
