# Disabled integration tests per https://broadworkbench.atlassian.net/browse/DT-2032
name: Integration Tests (DISABLED per DT-2032)

# This workflow is disabled - using a trigger that will never fire
on:
  workflow_dispatch:
    inputs:
      disabled:
        description: 'This workflow is disabled'
        required: false
        default: 'true'

jobs:
  # All jobs are disabled per https://broadworkbench.atlassian.net/browse/DT-2032
  disabled-notice:
    runs-on: ubuntu-latest
    steps:
      - name: Display disabled notice
        run: |
          echo "::notice::Integration tests are disabled per https://broadworkbench.atlassian.net/browse/DT-2032"
          exit 0
