name: Trivy Vulnerability Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # runs at 8 AM UTC, 4 AM EST.

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build all projects without running tests
        run: ./gradlew --build-cache build -x test

      - name: Construct docker image name and tag
        id: image-name
        run: |
          GITHUB_REPO=$(basename ${{ github.repository }})
          GIT_SHORT_HASH=$(git rev-parse --short HEAD)
          echo ::set-output name=name::${GITHUB_REPO}:${GIT_SHORT_HASH}

      - name: Build image locally with jib
        run: |
          ./gradlew --build-cache :service:jibDockerBuild \
            --image=${{ steps.image-name.outputs.name }} \
            -Djib.console=plain

      - name: Run Trivy vulnerability scanner
        uses: broadinstitute/dsp-appsec-trivy-action@v1
        with:
          image: ${{ steps.image-name.outputs.name }}

  notify-slack:
    needs: [ trivy ]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Notify slack on failure
        uses: broadinstitute/action-slack@v3.8.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel: '#jade-data-explorer'
          status: failure
          author_name: Build on dev
          fields: workflow,message
          text: 'Trivy failure :sadpanda:'
          username: 'Data Explorer GitHub Action'
