name: Trivy scan
on: [ pull_request ]

jobs:
  appsec-trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Construct docker image name and tag
        id: image-name
        run: echo ::set-output name=name::${{ github.event.repository.name }}:$(git rev-parse --short HEAD)

      - name: Build docker image locally using Jib
        run: |
          set -o pipefail
          ./gradlew :service:jibDockerBuild \
            --image=${{ steps.image-name.outputs.name }} \
            -Djib.console=plain

      - name: Run Trivy vulnerability scanner
        # Link: https://github.com/broadinstitute/dsp-appsec-trivy-action
        uses: broadinstitute/dsp-appsec-trivy-action@v1
        with:
          image: ${{ steps.image-name.outputs.name }}
